### ISSUE TITLE
HDFView-3.3.0-win10_64-vs16 crashes opening a HDF4 file.

### ISSUE THREAD

**Issue by hyoklee** [HDFGroup/hdfview#119]
Test with the attached file. I tested it on Windows 10.

[AIRS.2023.03.24.240.L2.SUBS2SUP.v7.0.7.0.G23084133451.hdf.gz](https://github.com/HDFGroup/hdfview/files/11262358/AIRS.2023.03.24.240.L2.SUBS2SUP.v7.0.7.0.G23084133451.hdf.gz)

**Comment by oyarzun** [comment]
Looks like the HDF4 library is failing to load properly
```
C:\Users\christian.oyarzun\Desktop\HDFViewApp-3.3.0-win10_64-vs17\HDFView>.\HDFView.exe
SLF4J: Class path contains multiple SLF4J providers.
SLF4J: Found provider [org.slf4j.simple.SimpleServiceProvider@2145433b]
SLF4J: Found provider [org.slf4j.nop.NOPServiceProvider@2890c451]
SLF4J: See https://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual provider is of type [org.slf4j.simple.SimpleServiceProvider@2145433b]
[main] INFO hdf.hdf5lib.H5 - HDF5 library: hdf5_java
[main] INFO hdf.hdf5lib.H5 -  successfully loaded from java.library.path
[main] INFO hdf.view.HDFView - Current directory is C:\Users\christian.oyarzun\Desktop\HDFViewApp-3.3.0-win10_64-vs17\HDFView
[main] INFO hdf.view.HDFView - Menubar created
[main] INFO hdf.view.HDFView - Toolbar created
[main] INFO hdf.view.HDFView - URL Toolbar created
[main] INFO hdf.view.HDFView - Content Area created
[main] INFO hdf.view.HDFView - Main Window created
[main] INFO hdf.hdflib.HDFLibrary - HDF4 library: hdf_java
[main] INFO hdf.hdflib.HDFLibrary -  NOT successfully loaded from java.library.path
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class hdf.hdflib.HDFLibrary
        at hdf.object.h4.H4File.isThisType(H4File.java:207)
        at hdf.view.TreeView.DefaultTreeView.openFile(DefaultTreeView.java:2374)
        at hdf.view.HDFView.openLocalFile(HDFView.java:1922)
        at hdf.view.HDFView$28.widgetSelected(HDFView.java:1037)
        at swt/org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
        at swt/org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
        at swt/org.eclipse.swt.widgets.Display.sendEvent(Display.java:4256)
        at swt/org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
        at swt/org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4054)
        at swt/org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3642)
        at hdf.view.HDFView.runMainWindow(HDFView.java:428)
        at hdf.view.HDFView$41.run(HDFView.java:2695)
        at swt/org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:183)
        at swt/org.eclipse.swt.widgets.Display.syncExec(Display.java:4785)
        at hdf.view.HDFView.main(HDFView.java:2686)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: 'int hdf.hdflib.HDFLibrary.HDdont_atexit()' [in thread "main"]
        at jarhdf@4.2.16/hdf.hdflib.HDFLibrary.HDdont_atexit(Native Method)
        at jarhdf@4.2.16/hdf.hdflib.HDFLibrary.loadH4Lib(HDFLibrary.java:238)
        at jarhdf@4.2.16/hdf.hdflib.HDFLibrary.<clinit>(HDFLibrary.java:165)
        at hdf.object.h4.H4File.isThisType(H4File.java:207)
        at hdf.view.TreeView.DefaultTreeView.openFile(DefaultTreeView.java:2374)
        at hdf.view.HDFView.openLocalFile(HDFView.java:1918)
        ... 12 more
Failed to launch JVM
```

**Comment by byrnHDF** [comment]
Did install the HDFView with Installer or the Application Image version? The Application Image version requires you to setup all paths on windows for finding dlls.

**Comment by byrnHDF** [comment]
Might be an object library HDF4 datatype error.

**Comment by hyoklee** [comment]
@byrnHDF , you can tell from file name in the title of this issue, can't you?

**Comment by byrnHDF** [comment]
Upon further testing on a linux machine, this file crashes on opening as well.  Must be something in the type of object trying to be opened.

**Comment by oyarzun** [comment]
@byrnHDF FYI, I've tried both the HDFView Windows installer and the application image. Both result in the same exception when trying to open any HDF4 file.

**Comment by byrnHDF** [comment]
A quick fix is to install the hdf-4.2.16 release - this will add whatever is missing from hdf in hdfview.
There must be a dll that needs to be copied.

**Comment by hyoklee** [comment]
@loricooperhdf , this is a HDF Newsletter item.

**Comment by byrnHDF** [comment]
The problem with the file is a hdf4 JNI issue See https://github.com/HDFGroup/hdf4 issue #355

**Comment by byrnHDF** [comment]
Fix will be in next release
