### ISSUE TITLE
HDFView 3.3.2 Compound Type Table View Error

### ISSUE THREAD

**Issue by hyoklee** [HDFGroup/hdfview#286]
OS: macos-12

Test file: https://nisar.asf.earthdatacloud.nasa.gov/NISAR-SAMPLE-DATA/GSLC/ALOS1_Rosamond_20081012/NISAR_L2_PR_GSLC_001_005_A_219_2005_DHDH_A_20081127T060959_20081127T061015_P01101_F_N_J_001.h5

Dataset: /science/LSAR/GSLC/grids/frequencyA/HH

<img width="999" alt="NISAR_L2_HH_compound_tv_err" src="https://github.com/HDFGroup/hdfview/assets/4994401/a80a875b-aadb-4f9a-ab17-d9858fed5785">

**Comment by byrnHDF** [comment]
Likely the problem is the size of the dataset exceeded the memory available, as I was able to open it on a test machine with large available memory.
This is a known problem with HDFView.

**Comment by hyoklee** [comment]
Windows 11 + 32G memory machine: 

```
Caused by: java.lang.OutOfMemoryError: Java heap space
        at hdf.object.h5.H5CompoundDS.compoundTypeIO(H5CompoundDS.java:1036)
        at hdf.object.h5.H5CompoundDS.compoundDatasetCommonIO(H5CompoundDS.java:867)
        at hdf.object.h5.H5CompoundDS.read(H5CompoundDS.java:767)
        at hdf.object.Dataset.getData(Dataset.java:667)
```

**Comment by hyoklee** [comment]
ViTables works fine.

![vitables_NISAR_L2](https://github.com/HDFGroup/hdfview/assets/4994401/7029978d-f2b0-46a9-87d2-92d9efa35b87)
